language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories:
  - node_modules
  - dist
before_install:
- openssl aes-256-cbc -K $encrypted_564a5f20e1d7_key -iv $encrypted_564a5f20e1d7_iv
  -in deploy.js.enc -out deploy.js -d
script:
- yarn lint
- yarn build
- yarn deploy
